kynet: Pin quinn-proto version
Even though quinn is pinned to version 0.11.8, its dependency
quinn-proto uses the latest available version. Since quinn
re-exports quinn-proto structures, clippy or build errors may occur
depending on whichever version of quinn-proto ends up being used.

    error: use of deprecated associated function `quinn::ClientConfig::with_platform_verifier`:
           use `try_with_platform_verifier()` instead
       --> kynet/src/driver/quinn.rs:115:34
        |
    115 |             quinn::ClientConfig::with_platform_verifier()
        |                                  ^^^^^^^^^^^^^^^^^^^^^^
        |