kyproto: Fix documentation format
Use //! so that the documentation applies to the module.

This fixes clippy warnings like this one:

    error: empty line after doc comment
      --> kyproto/src/protocol/driver/av/video_gopstream.rs:16:1
       |
    16 | / /**
    17 | |  * This protocol opens a new QUIC stream for every GOP (group of pictures).
    18 | |  *
    19 | |  * Concretely, a new QUIC stream is started on every keyframe.
    ...  |
    78 | |  */
    79 | |
       | |_^
    80 |   pub(crate) struct VideoGopStreamProtocolSendDriver {
       |   -------------------------------------------------- the comment documents this struct