kymux/tests: Reduce the number of concurrent task
This is a workaround to an issue we have on macOS runner
since macOS upgrade.

thread 'tokio-runtime-worker' panicked at kymux/tests/integration_tests.rs:150:38:
called `Result::unwrap()` on an `Err` value: Os { code: 55, kind: Uncategorized, message: "No buffer space available" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2025-09-02T10:47:19.020Z INFO  kycom] VideoClientEndpoint> forwarder ended with result Os { code: 55, kind: Uncategorized, message: "No buffer space available" }
[2025-09-02T10:47:19.020Z INFO  kycom] VideoClientEndpoint> forwarder ended with result Os { code: 55, kind: Uncategorized, message: "No buffer space available" }
[2025-09-02T10:47:19.020Z INFO  kycom] VideoClientEndpoint> forwarder ended with result Os { code: 55, kind: Uncategorized, message: "No buffer space available" }
[2025-09-02T10:47:19.020Z INFO  kycom] VideoClientEndpoint> forwarder ended with result Os { code: 55, kind: Uncategorized, message: "No buffer space available" }
[2025-09-02T10:47:19.020Z INFO  kycom] VideoClientEndpoint> forwarder ended with result Os { code: 55, kind: Uncategorized, message: "No buffer space available" }
...
thread 'stress_test' panicked at kymux/tests/integration_tests.rs:596:17:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(31), "called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: \"Broken pipe\" }", ...)
[2025-09-02T10:47:40.475Z ERROR kyproto::router] RouterError("read_datagram() failed: ConnectionError(\"closed\")")
[2025-09-02T10:47:40.475Z ERROR kyproto::router] RouterError("accept_bi() failed: ConnectionError(\"closed\")")
failures:
    stress_test
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 24.40s